### PR TITLE
Adding includeStyle option to allow stripping style from console logger. Defaults to yes.

### PR DESCRIPTION
**Pull request by aheuermann**
- [x] @doug-martin 
- [ ] @dustinsmith1024

### CODE REVIEW

**Comment by aheuermann** [comment]
I debated on this vs creating a whole separate appender. 
Could also rename current `ConsoleAppender` to `StyledConsoleAppender` and make the current style-less. If either of you have strong opinions, let me know. I don't mind updating.

**Comment by doug-martin** [comment]
I think it makes sense to include this in the ConsoleAppender.

**Comment by aheuermann** [comment]
On second thought, this may not be needed. It looks like papertrail supports ANSI color codes, but rsyslog may be escaping them by default. I'm going to talk to Robert tomorrow about getting this disabled. I may leave as-is or update to just color the log level.

**Comment by aheuermann** [comment]
@doug-martin This is ready to review again. I changed the property to `wrapStyle` and added a `levelNameColored` property.

**Comment by doug-martin** [comment]
@aheuermann looks good

**Pull request merged**
